networks:
  caddy:
    external: true

volumes:
  kms-db:

services:
  kms:
    image: pykmsorg/py-kms:python3
    ports:
      - 1688:1688 # kms
    labels:
      - caddy=https://kms.gana-loterias.online
      - caddy.reverse_proxy="{{upstreams 8080}}"
    networks:
      - caddy
    restart: always
    volumes:
      - kms-db:/home/py-kms/db