version: '3.8'

services:
  postgres-mdm:
    container_name: mdm-postgres
    image: postgres:14.1-alpine
    networks:
      - caddy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data-mdm:/var/lib/postgresql/data
    restart: always
  headwind:
    container_name: headwind
    image: headwindmdm/hmdm:latest
    labels:
      - caddy=https://${FRONTEND_URL}
      - caddy.reverse_proxy="{{upstreams 8080}}"
    networks:
      - caddy
    environment:
      SQL_BASE: ${POSTGRES_DB}
      SQL_HOST: postgres-mdm
      SQL_USER: ${POSTGRES_USER}
      SQL_PASS: ${POSTGRES_PASSWORD}
      BASE_DOMAIN: ${FRONTEND_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      FORCE_RECONFIGURE: true
      PROTOCOL: http
    depends_on:
      - postgres-mdm
    ports:
      - 31000:31000
    volumes:
      - letsencrypt:/etc/letsencrypt
      - work:/usr/local/tomcat/work
    restart: always
    links:
      - postgres-mdm

volumes:
  postgres-data-mdm:
  letsencrypt:
  work:

networks:
  caddy:
    external: true
