version: '3.8'

services:
  postgres:
    container_name: odoo-postgres
    image: postgres:14.1-alpine
    networks:
      - caddy
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    labels:
      - caddy=${PGADMIN_URL}
      - caddy.reverse_proxy="{{upstreams 8080}}"
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    networks:
      - caddy
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  odoo:
    container_name: odoo
    image: odoo:17.0
    labels:
      - caddy=${FRONTEND_URL}
      - caddy.reverse_proxy="{{upstreams 8069}}"
    networks:
      - caddy
    environment:
      HOST: postgres
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - 8069:8069
    volumes:
      - config:/etc/odoo
      - extra-addons:/mnt/extra-addons
      - data:/var/lib/odoo
    restart: always
    links:
      - postgres

volumes:
  postgres-data:
  config:
  extra-addons:
  data:
  pgadmin-data:

networks:
  caddy:
    external: true
