networks:
  caddy:
    external: true
  typebot_network:

volumes:
  db-data:

services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - caddy
      - typebot_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    labels:
      caddy: ${BUILDER_URL}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    depends_on:
      - typebot-db
    networks:
      - caddy
      - typebot_network
    env_file: stack.env

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    labels:
      caddy: ${VIEWER_URL}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: always
    networks:
      - typebot_network
      - caddy
    env_file: stack.env